### ISSUE TITLE
Parse/Serialize from/to Js.Json.t

### ISSUE THREAD

**Issue by cometkim** [DZakh/rescript-struct#27]
for better interoperability

**Comment by DZakh** [comment]
I have plans to add `let serializeToJsonWith: ('value, t<'value>) => Js.Json.t` in the next version since sometimes `Js.Json.t` is more comfortable to work with than `unknown`. Do you need the same for parsing or some other methods?

**Comment by cometkim** [comment]
Yes, because a framework already task Json.t encoder/decoder for its interface. But It's nice to have `parseFromStringWith`/`serializeToStringWith`.

BTW, I still don't understand how to use unknown correctly. It's intended to use with user-defined assertions?

**Comment by DZakh** [comment]
The `unknown` is an opaque type that represents unknown JavaScript value.

The only way to work with it is to do runtime checks and then cast the value to an expected type. Like here:
https://github.com/DZakh/rescript-struct/blob/2679cab5eef490ed656bd069598c13225acc5003/__tests__/S_JsApi_test.ts#L310-L325

I use `unknown` instead of `Js.Json.t` because `rescript-struct` works with any JavaScript values, not only serializable to JSON. Right now, there are not many built-in structs like this. Probably, I even deleted the only one in V3 release. But it's possible to construct them using `S.custom`. Also, there's a high chance that I'll add them in the future to allow parse `Date` instances, functions, promises, etc. 

For now, you can extend `ReScriptStruct` with your helper functions. To do so, you need to remove `"bsc-flags": ["-open ReScriptStruct"]` from the `bsconfig` and instead of it, create a `S.res` module in your application with the following content:
```
// S.res
include ReScriptStruct.S

let serializeToJsonWith = {
  let castResultWithUnknownToResultWithJson: result<unknown, Error.t> => result<
    Js.Json.t,
    Error.t,
  > = Obj.magic

  (value: 'value, struct: t<'value>): result<Js.Json.t, Error.t> => {
    value->serializeWith(struct)->castResultWithUnknownToResultWithJson
  }
}

let serializeToJsonStringWith = {
  (value: 'value, struct: t<'value>): result<string, Error.t> => {
    value->serializeToJsonWith(struct)->Belt.Result.map(Js.Json.stringify)
  }
}

let parseFromJsonWith: (Js.Json.t, t<'value>) => result<'value, Error.t> = parseWith

let parseFromJsonStringWith = (jsonString: string, struct: t<'value>): result<'value, Error.t> => {
  try {Ok(jsonString->Js.Json.parseExn)} catch {
  | _ =>
    Error({
      Error.code: OperationFailed("Couldn't parse JSON string."),
      operation: Parsing,
      path: [],
    })
  }->Belt.Result.flatMap(json => json->parseWith(struct))
}
```

It includes a little bit of unsafe casting from `unknown` to `Js.Json.t`, but unless you don't use `S.custom` it should be fine.

**Comment by DZakh** [comment]
@cometkim Could you check out the PR https://github.com/DZakh/rescript-struct/pull/35? Do you have any comments/suggestions?

**Comment by cometkim** [comment]
I will try!

**Comment by DZakh** [comment]
`rescript-struct@4.0.0` is now published. You can find the release notes here: https://github.com/DZakh/rescript-struct/releases/tag/v4.0.0
